services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:${DIP_INFRA_NGINX_PROXY_IMAGE_TAG}
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80

volumes:
  redis:

networks:
  default:
    name: ${DIP_INFRA_NETWORK_NAME}
    external: true
